  clear; close all;clc;
% Import the data generated by script "cilia_direction_calculation_version2"
  [filename, pathname]=uigetfile('*.mat','please select the mat file generated by script cilia_direction_calculation_version2');
  cd(pathname);
  data=importdata(filename);
  direction=data.dp(:,6); % direction [-pi,pi]
% Caculate the following parameters: 
 % circ_r: Resultant vector length;
 % circ_mean: Mean direction of a sample of circular data;
 % circ_rtest? Rayleigh's test for nonuniformity;
  vector_length=circ_r(direction); 
  mean_direction=circ_mean(direction);
  [p_value,z_value]=circ_rtest(direction);
 % Save the generated data
  save([filename(1:end-4) '_generateddata2.mat']);
  display('--------------------------------------------------------------');
  display('the mean direction of the cell is:');
  display(num2str(mean_direction));
  display('the vector length of the cell is:');
  display(num2str(vector_length));
  display('the p_value is:');
  display(num2str(p_value));
  display('--------------------------------------------------------------');